name: Renovate

on:
  schedule:
    - cron: '0 2 * * 6'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}
          repositories: 'fastlane-plugin-screenshotbot'
      
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@d65ef9e20512193cc070238b49c3873a361cd50c
        with:
          configurationFile: renovate.yaml
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'