name: Renovate

on:
  schedule:
    - cron: '0 2 * * 6'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}
          repositories: 'fastlane-plugin-screenshotbot'
      
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@664826b7a1041134b41f6c2c55e8bead06f46f8d
        with:
          configurationFile: renovate.yaml
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'